loading_params:
    source_resample_ratio: 0.5
    target_resample_ratio: 0.5
echo: True
initial_registration_params:
    echo: True
    run_superpoint_ransac: True
    angle_step: 2
    registration_size: 2048
    registration_sizes: [50,100,125,150,175,200,225,250]
